server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    youtubeSearchEnabled: true
    gc-warnings: true
    plugins: []

metrics:
  prometheus:
    enabled: false

logging:
  file:
    enabled: false
  level:
    root: INFO
